options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build the Docker image with the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'us-central1-docker.pkg.dev/hkd-reporting/github-service-sheettobigquery/service-sheettobigquery:latest',
      '.'
    ]

  # Step 2: Push the latest tag to the Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/hkd-reporting/github-service-sheettobigquery/service-sheettobigquery:latest']

  # Step 3: Deploy the latest tag to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Deploy to Cloud Run with secrets linked as environment variables
        gcloud run deploy service-sheettobigquery \
          --image us-central1-docker.pkg.dev/hkd-reporting/github-service-sheettobigquery/service-sheettobigquery:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --timeout 1800 \
          --memory 1Gi \
          --max-instances 20 \
          --concurrency 5 \
          --cpu 1 \
          --set-secrets google_cloud_hkdreporting=google_cloud_hkdreporting:latest,slack_accessToken=slack_accessToken:latest

images:
  - 'us-central1-docker.pkg.dev/hkd-reporting/github-service-sheettobigquery/service-sheettobigquery:latest' 